config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionnaire
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers,
        :reject_if => lambda { |a| a[:content].blank? },
        :allow_destroy => true
end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  has_many :questions, dependent: :destroy

accepts_nested_attributes_for :questions,
        :reject_if => lambda { |a| a[:content].blank? },
        :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  # GET /questionnaires
  # GET /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.json
  def show
    @questionnaire = Questionnaire.find(params[:id])
    @questions = @questionnaire.questions
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
    params[:num_questions].to_i.times do
      question = @questionnaire.questions.build
      params[:num_answers].to_i.times { question.answers.build }
    end
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  # POST /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully created.' }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1
  # PATCH/PUT /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1
  # DELETE /questionnaires/1.json
  def destroy
    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionnaire_params
      params.require(:questionnaire).permit(:name,
          questions_attributes: [:content,
              answers_attributes: [:content]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Survey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questionnaires/_form.html.erb
<%= form_for(@questionnaire) do |f| %>
  <% if @questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
      <% @questionnaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2>Questionnaire Name</h2>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.fields_for :questions do |question| %>
      <h3>Question</h3>
      <%= question.text_field :content %>
        <%= question.fields_for :answers do |answer| %>
          <h3>Answer</h3>
          <%= answer.text_field :content %>
      <% end %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questionnaires/edit.html.erb
<h1>Editing Questionnaire</h1>

<%= render 'form' %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questionnaires</h1>

<%= form_tag(new_questionnaire_path, method: 'get') do %>
  <p>
    Choose number of questions<br>
    <%= select_tag(:num_questions, options_for_select(1..10)) %>
  </p>
  <p>
    Choose number of possibe answers<br>
    <%= select_tag(:num_answers, options_for_select(1..5)) %>
  </p>
  <%= submit_tag "Create Questionnaire" %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaires.each do |questionnaire| %>
    <tr>
      <td><%= questionnaire.name %></td>
      <td><%= link_to 'Show', questionnaire %></td>
      <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %></td>
      <td><%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/questionnaires/new.html.erb
<h1>New Questionnaire</h1>

<%= render 'form' %>

<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @questionnaire.name %></h1><br>

<% @questions.each do |q| %>
<h2><%= q.content %></h2>
  <% q.answers.each do |a| %>
  <p><%= a.content %></p>
  <% end %>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @questionnaire.name %>
</p>

<%= link_to 'Edit', edit_questionnaire_path(@questionnaire) %> |
<%= link_to 'Back', questionnaires_path %>